/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Fulvio
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btNewCamp = new javax.swing.JButton();
        btNewPraca = new javax.swing.JButton();
        btEdtExcCamp = new javax.swing.JButton();
        btEdtExcPracas = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Marketing");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Marketing");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        btNewCamp.setText("<html>Cadastrar novas <br>Campanhas</html>");
        btNewCamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewCampActionPerformed(evt);
            }
        });
        getContentPane().add(btNewCamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 55));

        btNewPraca.setText("<html>Cadastrar novas <br>praças</html>");
        btNewPraca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewPracaActionPerformed(evt);
            }
        });
        getContentPane().add(btNewPraca, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 120, 55));

        btEdtExcCamp.setText("<html>Editar/excluir Campanhas</html>");
        btEdtExcCamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEdtExcCampActionPerformed(evt);
            }
        });
        getContentPane().add(btEdtExcCamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 110, 50));

        btEdtExcPracas.setText("<html>Editar/excluir Praças</html>");
        btEdtExcPracas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEdtExcPracasActionPerformed(evt);
            }
        });
        getContentPane().add(btEdtExcPracas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 120, 50));

        btFechar.setText("<html>fechar</html>");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNewCampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewCampActionPerformed
     CadastroCampanhas frame = new CadastroCampanhas(); frame.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_btNewCampActionPerformed

    private void btNewPracaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewPracaActionPerformed
     CadastroPracas frame = new CadastroPracas(); frame.setVisible(true);   // TODO add your handling code here:

    }//GEN-LAST:event_btNewPracaActionPerformed

    private void btEdtExcCampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEdtExcCampActionPerformed
     EditarCampanhas frame = new EditarCampanhas(); frame.setVisible(true);   // TODO add your handling code here:

    }//GEN-LAST:event_btEdtExcCampActionPerformed

    private void btEdtExcPracasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEdtExcPracasActionPerformed
     EditarPracas frame = new EditarPracas(); frame.setVisible(true);   // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_btEdtExcPracasActionPerformed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
    this.dispose();
        
    }//GEN-LAST:event_btFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEdtExcCamp;
    private javax.swing.JButton btEdtExcPracas;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btNewCamp;
    private javax.swing.JButton btNewPraca;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
